export const imgW4lbl = {
        "items": [
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "text": "Family",
                    "x": 24,
                    "y": 10,
                    "font": "50px Arial",
                    "translate": true,
                    "command": "text",
                    "name": "text_d",
                    "color": "#e30202",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 6,
                    "shadowOffsetY": 6,
                    "shadowColor": "#bc8585",
                    "shadowBlur": 4,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d0"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "text": "Execution",
                    "x": 1,
                    "y": 9,
                    "font": "50px Arial",
                    "translate": true,
                    "command": "text",
                    "name": "text_c",
                    "color": "#e30202",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 6,
                    "shadowOffsetY": 6,
                    "shadowColor": "#bc8585",
                    "shadowBlur": 4,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d1"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "text": "Group Activity",
                    "x": 21,
                    "y": 3,
                    "font": "50px Arial",
                    "translate": true,
                    "command": "text",
                    "name": "text_b",
                    "color": "#e30202",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 6,
                    "shadowOffsetY": 6,
                    "shadowColor": "#bc8585",
                    "shadowBlur": 4,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d2"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "text": "Planning Stage",
                    "x": 1,
                    "y": 3,
                    "font": "50px Arial",
                    "translate": true,
                    "command": "text",
                    "name": "text_a",
                    "color": "#e30202",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 6,
                    "shadowOffsetY": 6,
                    "shadowColor": "#bc8585",
                    "shadowBlur": 4,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d3"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "spriteId": "000",
                    "sheet": "people",
                    "sheetItem": "mom_kids_study",
                    "dx": 33,
                    "dy": 9,
                    "wFactor": 0.5,
                    "hFactor": 0.5,
                    "translate": true,
                    "command": "sprite",
                    "name": "sprite_d",
                    "color": "red",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d4"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "spriteId": "000",
                    "sheet": "people",
                    "sheetItem": "crowd",
                    "dx": 11,
                    "dy": 8,
                    "wFactor": 0.5,
                    "hFactor": 0.5,
                    "translate": true,
                    "command": "sprite",
                    "name": "sprite_c",
                    "color": "red",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d5"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "spriteId": "000",
                    "sheet": "people",
                    "sheetItem": "mf_wlk_biz",
                    "dx": 35,
                    "dy": 1,
                    "wFactor": 0.5,
                    "hFactor": 0.5,
                    "translate": true,
                    "command": "sprite",
                    "name": "sprite_b",
                    "color": "red",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d6"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "spriteId": "000",
                    "sheet": "people",
                    "sheetItem": "man_tblt_stndg",
                    "dx": 16,
                    "dy": 1,
                    "wFactor": 0.5,
                    "hFactor": 0.5,
                    "translate": true,
                    "command": "sprite",
                    "name": "sprite_a",
                    "color": "red",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d7"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "x1": 20,
                    "y1": 0,
                    "x2": 20,
                    "y2": 15,
                    "lineWidth": 2,
                    "translate": true,
                    "command": "line",
                    "name": "line_ver",
                    "color": "#b9b6b6",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d8"
            },
            {
                "name": "",
                "content": "",
                "showAt": 0,
                "extra": {
                    "x1": 0,
                    "y1": 7,
                    "x2": 40,
                    "y2": 7,
                    "lineWidth": 2,
                    "translate": true,
                    "command": "line",
                    "name": "line_hor",
                    "color": "#b9b6b6",
                    "hideAt": 0,
                    "showAt": 0,
                    "visibility": 0,
                    "globalAlpha": 1,
                    "gap": 0,
                    "dash": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0,
                    "shadowColor": "gray",
                    "shadowBlur": 0,
                    "useShowHide": false
                },
                "arr": [],
                "_id": "665ba7ddba9a237f5dd749d9"
            }
        ],
        "extra": {
            "backgroundColor": "#03260A",
            "canvasWidth": 1000,
            "canvasHeight": 360,
            "cellHeight": 25,
            "cellWidth": 25,
            "xFactor": 0,
            "yFactor": 0,
            "showGrid": false,
            "bgGlobalAlpha": 1,
            "gridLineWidth": 1,
            "gridLineColor": "#363C34",
            "bgImg": "systemImages/white_mat.jpg"
        }
    }