export const imgW3lbl = {
    
    "items": [
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "text": "Execution",
                "x": 30,
                "y": 11,
                "font": "30px Arial",
                "translate": true,
                "command": "text",
                "name": "text_c",
                "color": "#e30202",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "#bc8585",
                "shadowBlur": 4,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d2"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "spriteId": "000",
                "sheet": "people",
                "sheetItem": "old_cpl_jog",
                "dx": 30,
                "dy": 2,
                "wFactor": 0.75,
                "hFactor": 0.75,
                "translate": true,
                "command": "sprite",
                "name": "sprite_c",
                "color": "red",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d6"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "x1": 12,
                "y1": 0,
                "x2": 12,
                "y2": 15,
                "lineWidth": 2,
                "translate": true,
                "command": "line",
                "name": "line_ver2",
                "color": "#b9b6b6",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d8"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "text": "Group Activity",
                "x": 15,
                "y": 11,
                "font": "30px Arial",
                "translate": true,
                "command": "text",
                "name": "text_b",
                "color": "#e30202",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "#bc8585",
                "shadowBlur": 4,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d2"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "text": "Planning Stage",
                "x": 1,
                "y": 11,
                "font": "30px Arial",
                "translate": true,
                "command": "text",
                "name": "text_a",
                "color": "#e30202",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "#bc8585",
                "shadowBlur": 4,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d3"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "spriteId": "000",
                "sheet": "people",
                "sheetItem": "mf_wlk_biz",
                "dx": 16,
                "dy": 2,
                "wFactor": 0.75,
                "hFactor": 0.75,
                "translate": true,
                "command": "sprite",
                "name": "sprite_b",
                "color": "red",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d6"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "spriteId": "000",
                "sheet": "people",
                "sheetItem": "man_tblt_stndg",
                "dx": 3,
                "dy": 2,
                "wFactor": 0.75,
                "hFactor": 0.75,
                "translate": true,
                "command": "sprite",
                "name": "sprite_a",
                "color": "red",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d7"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "x1": 26,
                "y1": 0,
                "x2": 26,
                "y2": 15,
                "lineWidth": 2,
                "translate": true,
                "command": "line",
                "name": "line_ver",
                "color": "#b9b6b6",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": [],
            "_id": "665ba7ddba9a237f5dd749d8"
        }
    ],
    "extra": {
        "backgroundColor": "#03260A",
        "canvasWidth": 1000,
        "canvasHeight": 360,
        "cellHeight": 25,
        "cellWidth": 25,
        "xFactor": 0,
        "yFactor": 0,
        "showGrid": false,
        "gridLineWidth": 1,
        "gridLineColor": "#363C34",
        "bgGlobalAlpha": 1,
        "bgImg": "systemImages/white_mat.jpg"
    }
}