export const jt1 = {
    "items": [
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "jt_30962441",
                "command": "text",
                "text": "This is The Title",
                "x": 14.5,
                "y": 5.5,
                "color": "#fa1900",
                "font": "80px Arial",
                "shadowOffsetX": 12,
                "shadowOffsetY": 12,
                "shadowColor": "#9D850B",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 12
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "3a",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 11,
                "dy": 5.5,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "2b",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 7.5,
                "dy": 7,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "2a",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 7.5,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "0",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 4,
                "dy": 1,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "1",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 4,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "2",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 4,
                "dy": 7,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "3",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 4,
                "dy": 10,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": []
        }
    ],
    "extra": {
        "backgroundColor": "#EEE9CE",
        "canvasWidth": 1000,
        "canvasHeight": 360,
        "cellHeight": 25,
        "cellWidth": 25,
        "xFactor": 0,
        "bgGlobalAlpha": 1,
        "yFactor": 0,
        "showGrid": false,
        "gridLineWidth": 1,
        "gridLineColor": "#605C52"
    }

}