export const rnl = {
    "items": [
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "-3/3",
                "command": "text",
                "text": "(-3/3)",
                "x": 8,
                "y": 4,
                "color": "#09f10d",
                "font": "30px Arial",
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "black",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 3
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73001"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "ray78684171",
                "command": "ray",
                "x0": 10,
                "y0": 5,
                "x1": 13.5,
                "y1": 8.5,
                "lineColor": "#04f634",
                "lineWidth": 2,
                "arrowWidth": 8,
                "arrowHeight": 12,
                "startArrow": false,
                "endArrow": true,
                "globalAlpha": 1,
                "useShowHide": false,
                "showAt": 0,
                "dash": 0,
                "gap": 0
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73002"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "text_88850759",
                "command": "text",
                "text": "(- 2/3)",
                "x": 14,
                "y": 4,
                "color": "#034efc",
                "font": "30px Arial",
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "black",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 3
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73003"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "ray32794918",
                "command": "ray",
                "x0": 16,
                "y0": 5,
                "x1": 17,
                "y1": 8.5,
                "lineColor": "#0231ed",
                "lineWidth": 2,
                "arrowWidth": 8,
                "arrowHeight": 12,
                "startArrow": false,
                "endArrow": true,
                "globalAlpha": 1,
                "useShowHide": false,
                "showAt": 0,
                "dash": 0,
                "gap": 0
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73004"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "text_26062860",
                "command": "text",
                "text": "(- 1/3)",
                "x": 22,
                "y": 4,
                "color": "#f21202",
                "font": "30px Arial",
                "shadowOffsetX": 6,
                "shadowOffsetY": 6,
                "shadowColor": "black",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 3
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73005"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "ray70060947",
                "command": "ray",
                "x0": 22,
                "y0": 5,
                "x1": 20.3,
                "y1": 8.5,
                "lineColor": "#f00505",
                "lineWidth": 2,
                "arrowWidth": 8,
                "arrowHeight": 12,
                "startArrow": false,
                "endArrow": true,
                "globalAlpha": 1,
                "useShowHide": false,
                "showAt": 0,
                "dash": 0,
                "gap": 0
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73006"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "-101",
                "command": "repeatText",
                "textArray": "-1,0,1",
                "initialX": 13.6,
                "initialY": 10,
                "xFactor": 9,
                "yFactor": 0,
                "color": "#efc701",
                "useShowHide": false,
                "showAt": 0,
                "font": "30px Arial"
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73007"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "dots-blue",
                "command": "repeatDot",
                "numberOfDots": 2,
                "initialX": 17,
                "initialY": 9,
                "xFactor": 3,
                "yFactor": 0,
                "width": 12,
                "useShowHide": false,
                "showAt": 0,
                "color": "#0240f7"
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73008"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "dots-red",
                "command": "repeatDot",
                "numberOfDots": 3,
                "initialX": 14,
                "initialY": 9,
                "xFactor": 9,
                "yFactor": 0,
                "width": 15,
                "useShowHide": false,
                "showAt": 0,
                "color": "#ff3300"
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd73009"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "ray85890806",
                "command": "ray",
                "x0": 7,
                "y0": 9,
                "x1": 38,
                "y1": 9,
                "lineColor": "#f6fa00",
                "lineWidth": 2,
                "arrowWidth": 8,
                "arrowHeight": 12,
                "startArrow": true,
                "endArrow": true,
                "globalAlpha": 1,
                "useShowHide": false,
                "showAt": 0,
                "dash": 0,
                "gap": 0
            },
            "arr": [],
            "_id": "664e9507ba9a237f5dd7300a"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "jt_26227226",
                "command": "text",
                "text": "Plot -1/3(-0.33) on Real Line",
                "x": 9,
                "y": 1,
                "color": "#FAE500",
                "font": "50px Arial",
                "shadowOffsetX": 12,
                "shadowOffsetY": 12,
                "shadowColor": "#9D850B",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 12
            },
            "arr": [],
            "_id": "664e9229ba9a237f5dd72f77"
        }
    ],
    "extra": {
        "backgroundColor": "#03260A",
        "canvasWidth": 1000,
        "canvasHeight": 360,
        "cellHeight": 25,
        "cellWidth": 25,
        "xFactor": 0,
        "yFactor": 0,
        "showGrid": true,
        "bgGlobalAlpha": 1,
        "gridLineWidth": 1,
        "gridLineColor": "#363C34"
    }

}