export const test = {
"items" :[
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "text_80984250",
                "command": "text",
                "text": "Bomb!!!!",
                "x": 24,
                "y": 8,
                "color": "#fa0000",
                "font": "40px Arial",
                "shadowOffsetX": 3,
                "shadowOffsetY": 3,
                "shadowColor": "#675151",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 3
            },
            "arr": [],
            "_id": "664e2a47ba9a237f5dd727a3"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "s",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "bomb",
                "dx": 24,
                "dy": 3,
                "wFactor": 1.5,
                "hFactor": 1.5,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 0,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e2a47ba9a237f5dd727a4"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "1",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 0,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 2,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd7270d"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "2",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 3,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 3,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd7270e"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "3",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 6,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 4,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd7270f"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "4",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 9,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 5,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd72710"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "5",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 12,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 6,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd72711"
        },
        {
            "name": "",
            "content": "",
            "showAt": 0,
            "extra": {
                "translate": true,
                "name": "6",
                "command": "sprite",
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 15,
                "dy": 4,
                "wFactor": 1,
                "hFactor": 1,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "useShowHide": false,
                "showAt": 7,
                "globalAlpha": 1,
                "shadowBlur": 0
            },
            "arr": [],
            "_id": "664e1f43ba9a237f5dd72712"
        }
    ],

    
    "extra" : {
        "backgroundColor": "#eae9e1",
        "canvasWidth": 1000,
        "canvasHeight": 360,
        "cellHeight": 25,
        "cellWidth": 25,
        "xFactor": 0,
        "yFactor": 7,
        "showGrid": false,
        "gridLineWidth": 1,
        "gridLineColor": "#605C52"
    }

}