export const h2li ={
    "items": [
        {
            "uuid": "de58e14d-e7e0-456e-a703-43116ae917ab",
            "name": "",
            "content": "",
            "showAt": 0,
            "hideAt": null,
            "extra": {
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 7,
                "dy": 9,
                "wFactor": 1,
                "hFactor": 1,
                "translate": true,
                "command": "sprite",
                "name": "li2-sprite",
                "color": "red",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": []
        },
        {
            "uuid": "ccc73a55-0c6d-44e5-8496-cce263069f91",
            "name": "",
            "content": "",
            "showAt": 0,
            "hideAt": null,
            "extra": {
                "text": "This is the second point.",
                "x": 11,
                "y": 9.5,
                "font": "50px Arial",
                "translate": true,
                "command": "text",
                "name": "li-2",
                "color": "#fa7900",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 2,
                "shadowOffsetY": 2,
                "shadowColor": "black",
                "shadowBlur": 4,
                "useShowHide": false
            },
            "arr": []
        },
        {
            "uuid": "ccc73a55-0c6d-44e5-8496-cce263069f91",
            "name": "",
            "content": "",
            "showAt": 0,
            "hideAt": null,
            "extra": {
                "text": "This is the first point.",
                "x": 11,
                "y": 5.5,
                "font": "50px Arial",
                "translate": true,
                "command": "text",
                "name": "li-1",
                "color": "#fa7900",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 2,
                "shadowOffsetY": 2,
                "shadowColor": "black",
                "shadowBlur": 4,
                "useShowHide": false
            },
            "arr": []
        },
        {
            "uuid": "de58e14d-e7e0-456e-a703-43116ae917ab",
            "name": "",
            "content": "",
            "showAt": 0,
            "hideAt": null,
            "extra": {
                "spriteId": "000",
                "sheet": "figs",
                "sheetItem": "flower1",
                "dx": 7,
                "dy": 5,
                "wFactor": 1,
                "hFactor": 1,
                "translate": true,
                "command": "sprite",
                "name": "li1-sprite",
                "color": "red",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 0,
                "shadowOffsetY": 0,
                "shadowColor": "gray",
                "shadowBlur": 0,
                "useShowHide": false
            },
            "arr": []
        },
        {
            "uuid": "52e8d8cc-a3a8-4c0b-868d-333dc9e484e8",
            "name": "",
            "content": "",
            "showAt": 0,
            "hideAt": null,
            "extra": {
                "text": "Main Heading",
                "x": 12,
                "y": 2,
                "font": "60px Arial",
                "translate": true,
                "command": "text",
                "name": "jt_19048287",
                "color": "#fa0000",
                "hideAt": 0,
                "showAt": 0,
                "visibility": 0,
                "globalAlpha": 1,
                "gap": 0,
                "dash": 0,
                "shadowOffsetX": 12,
                "shadowOffsetY": 12,
                "shadowColor": "#6a0b0b",
                "shadowBlur": 12,
                "useShowHide": false
            },
            "arr": []
        }
    ],
    "extra": {
        "backgroundColor": "#efebb8",
        "canvasWidth": 1000,
        "canvasHeight": 360,
        "cellHeight": 25,
        "cellWidth": 25,
        "bgImg": "systemImages/white_mat.jpg",
        "xFactor": 0,
        "yFactor": 0,
        "showGrid": false,
        "bgGlobalAlpha": 1,
        "gridLineWidth": 1,
        "gridLineColor": "gray"
    }
}

